name: Deploy to VPS

on:
  push:
    branches:
      - dev_buyanov_CI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: nokizzy.de
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/bgb
            git pull
            systemctl restart mybot
